import { createClient } from "@supabase/supabase-js";
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const { data } = await supabase.from("songs").select("title,slug,song_summary,citation_summary,status");
const pub = data.filter(s=>s.status==="published");
const hasSum = pub.filter(s=>s.song_summary && s.song_summary.trim());
const hasCit = pub.filter(s=>s.citation_summary && s.citation_summary.trim());
console.log(`published: ${pub.length} | song_summary set: ${hasSum.length} | citation_summary set: ${hasCit.length}`);
console.log("\nExample song_summary:");
const ex = hasSum[0];
if (ex) console.log(`[${ex.title}]\n${ex.song_summary}`);
